unbind C-b
set -g prefix `
bind ` send-prefix

set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'lost-melody/tmux-command-palette'
set -g @plugin 'lloydbond/tmux-floating-terminal'

# Default shell
set-option -g default-shell $SHELL

# Allow pasting image
set-option -g allow-passthrough on

# Split panes with h and v
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

# Start tab numbering from 1
set -g base-index 1
setw -g pane-base-index 1

# Reload config with ` r 
bind-key r source-file ~/.config/tmux/tmux.conf \; 

# Toggle synchronize panes with ` b to send same commands to all panes
bind-key b set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

# Toggle status line with ` y
bind-key y set -g status

# TMUX STATUSLINE CONFIGURATIONS 
set-option -g status-position "top"
set-option -g status-style bg=#282828,fg=#ebdbb2
set-option -g status-justify left

# I display the session name on the left:
set-option -g status-left '#[bg=#282828,fg=#ffffff,bold]#{?client_prefix,,   }#[bg=#282828,fg=#ffffff,bold]'

# I display the system uptime and current time on the right
set-option -g status-right "#[fg=#ffffff, bold] 󰺓 #(uptime | awk '{print $3}' | sed 's/,//')  󰔟 %R"

# I customize the appearance of window titles:
set-option -g window-status-current-format '#[bg=#00ff1d,fg=#282828] #I:#W#{?window_zoomed_flag, 󰊓 , }'
set-option -g window-status-format ' #I:#W#{?window_zoomed_flag, 󰊓 , }'

# Always renumber tabs to be 1, 2, 3 ...
set -g renumber-windows on
setw -g allow-rename on

# Open a path in vim in a new window: press ` o, type path, hit Enter
# bind-key o display-popup -E -d '$HOME' 'dir=$(FZF_DEFAULT_COMMAND="find . -type d -maxdepth 5" fzf) && tmux new-window -c "$HOME/$dir" "zsh -i -c \"vim $dir\""'

# Open a path in nvim via autojump: press ` o, type jump query, hit Enter
bind-key o command-prompt -p "$ nvim:" "run-shell \"tmux new-window -c '\$HOME' zsh -i -c 'vim \\\"\$(j %1)\\\"'\""

run '~/.config/tmux/plugins/tpm/tpm'
# run '~/.config/tmux/plugins/catppuccin/catppuccin.tmux'

